import type { Slice3Rule } from '../types';

/** Literal Slice 3 expectations. No production policy/accounting imports. */
export const SLICE3_BIBLE_RULES: readonly Slice3Rule[] = [
  {
    id: 'ALL-COND-MODALITY-01', category: 'conditioning',
    section: 'Conditioning modality and visible honesty',
    anchorQuote: 'Running exposure does not include:',
    statement: 'Conditioning modality identity follows actual typed content; off-feet work never becomes running by label.',
    applicableScenarios: ['early-offseason-healthy', 'multi-modality-conditioning'],
    expectation: { runningRequiresRunning: true, conditioningSeparate: true },
  },
  {
    id: 'OS-EARLY-COND-01', category: 'conditioning', section: 'Off-season conditioning',
    anchorQuote: 'early off season = no running and only light aerobic work / base building work.',
    statement: 'Early off-season conditioning is easy, aerobic/base/flush and off-feet.',
    applicableScenarios: ['early-offseason-healthy'],
    expectation: { allowedIntents: ['aerobic_base', 'flush'], allowedIntensity: ['easy'], running: 0, hardConditioning: 0 },
  },
  {
    id: 'ALL-COND-EXPOSURE-01', category: 'conditioning', section: 'Conditioning exposure accounting',
    anchorQuote: 'Team training and games count as conditioning load.',
    statement: 'Actual conditioning and anchors earn conditioning credit; trunk and recovery add-ons do not create hard conditioning.',
    applicableScenarios: ['inseason-mixed-team-accounting', 'hamstring-restriction-mixed', 'low-readiness-downgrade'],
    expectation: { actualContentCounts: true, supportHardConditioning: 0 },
  },
  {
    id: 'ALL-COND-MULTI-01', category: 'conditioning', section: 'Conditioning components',
    anchorQuote: 'A conditioning component is proper planned conditioning work that may sit on the same day as strength.',
    statement: 'Every explicitly represented conditioning option/modality remains observable without first-match collapse.',
    applicableScenarios: ['multi-modality-conditioning'],
    expectation: { modalities: ['bike', 'row'], count: 2 },
  },
  {
    id: 'OS-PWR-PHASE-01', category: 'power', section: 'Power phase rules',
    anchorQuote: 'Off-season\nBest time to build power properly because there is less game-day pressure.',
    statement: 'Early off-season has no power, mid permits primer only, and late may permit structurally valid contrast.',
    applicableScenarios: ['early-offseason-healthy', 'mid-offseason-primer', 'late-offseason-valid-contrast'],
    expectation: { early: 'none', mid: 'primer', late: ['primer', 'contrast'] },
  },
  {
    id: 'ALL-PWR-CONTRAST-01', category: 'power', section: 'Contrast training',
    anchorQuote: 'Contrast training means pairing a heavy strength movement with an explosive movement that uses a similar pattern.',
    statement: 'Contrast requires a surviving same-family heavy lift and explosive movement.',
    applicableScenarios: ['late-offseason-valid-contrast', 'late-offseason-invalid-contrast'],
    expectation: { requiresHeavyLift: true, requiresSameFamily: true },
  },
  {
    id: 'ALL-PWR-CONTENT-01', category: 'power', section: 'Power content ownership',
    anchorQuote: 'Power work is not conditioning. It should be fast, sharp and high quality.',
    statement: 'Final power metadata and visible identity agree with final surviving strength and power content.',
    applicableScenarios: ['mid-offseason-primer', 'late-offseason-valid-contrast', 'late-offseason-invalid-contrast'],
    expectation: { contentOwnsIdentity: true },
  },
  {
    id: 'IS-PWR-PROXIMITY-01', category: 'power', section: 'G-relative power',
    anchorQuote: 'A tiny low-volume neural/power exposure may be okay for experienced athletes, but it is not a proper lower session.',
    statement: 'G-1/game/G+1 prohibit power; G-2 permits only the narrow tiny experienced neural-primer exception.',
    applicableScenarios: ['inseason-game-sat-g2-lower'],
    expectation: { g2Maximum: 'primer', game: 'none', gMinus1: 'none', gPlus1: 'none' },
  },
  {
    id: 'ALL-SPACE-G2-LOWER-01', category: 'spacing', section: 'G-2 freshness',
    anchorQuote: 'G-2 should not have a full hard lower session.',
    statement: 'Canonical squat/hinge content at G-2 is moderated or removed; names are not the detector.',
    applicableScenarios: ['inseason-game-sat-g2-lower'],
    expectation: { heavyLowerAtG2: false, maximumIntensity: 'Moderate' },
  },
  {
    id: 'ALL-SPACE-HARD-01', category: 'spacing', section: 'Hard-load spacing',
    anchorQuote: 'What should never be placed 1-2 days before a game: hard conditioning',
    statement: 'Extra hard lower, conditioning and sprint/COD do not cluster inside the protected game window.',
    applicableScenarios: ['inseason-game-sat-g2-lower', 'inseason-mixed-team-accounting'],
    expectation: { maxHardDays: 4, noExtraHardG1G2: true },
  },
  {
    id: 'ALL-ANCHOR-LOAD-01', category: 'spacing', section: 'Team/game anchors',
    anchorQuote: 'Team training often happens on G-2. That is accepted as normal club load.',
    statement: 'Team and game anchors count load but never invent squat/hinge/push/pull strength credit.',
    applicableScenarios: ['inseason-mixed-team-accounting'],
    expectation: { teamAnchors: 1, gameAnchors: 1, anchorStrengthPatterns: 0 },
  },
  {
    id: 'ALL-CONSTRAINT-AFFECTED-ONLY-01', category: 'constraint', section: 'Injury train-around',
    anchorQuote: 'keep safe training in the program where possible',
    statement: 'Affected content changes with evidence while unrelated strength and conditioning remain.',
    applicableScenarios: ['hamstring-restriction-mixed'],
    expectation: { removed: ['Romanian Deadlift'], preserved: ['Bench Press', 'Bike Aerobic Base'], evidenceRequired: true },
  },
  {
    id: 'ALL-EQUIPMENT-COMPATIBLE-01', category: 'constraint', section: 'Equipment train-around',
    anchorQuote: 'Do not force normal gym programming if they are away from equipment.',
    statement: 'Unavailable equipment is absent from final content while an existing compatible same-pattern option survives.',
    applicableScenarios: ['equipment-no-barbell-lower'],
    expectation: { removed: ['Back Squat'], preserved: ['Bulgarian Split Squat'], unavailable: ['Barbell', 'Rack'] },
  },
  {
    id: 'ALL-READINESS-DOWNGRADE-01', category: 'constraint', section: 'Readiness reduction',
    anchorQuote: 'If the athlete is cooked, sick, sore or injured, reduce conditioning first before smashing strength.',
    statement: 'Low readiness removes hard extras/power first and preserves safe main work with evidence.',
    applicableScenarios: ['low-readiness-downgrade'],
    expectation: { power: 'none', hardConditioning: 0, preserveStrength: true },
  },
  {
    id: 'ALL-EXPOSURE-STRENGTH-01', category: 'exposure', section: 'Strength exposure accounting',
    anchorQuote: 'This does not include:\nGunshow\nAccessories\nMobility\nRecovery\nLight prehab',
    statement: 'Mixed and Team Training + Strength receive effective regional strength credit; accessory/support do not.',
    applicableScenarios: ['inseason-mixed-team-accounting'],
    expectation: { mainStrength: 2, lowerFatigue: 1, upperFatigue: 1 },
  },
  {
    id: 'ALL-EXPOSURE-COND-01', category: 'exposure', section: 'Conditioning exposure accounting',
    anchorQuote: 'In-season, team training and games count as conditioning load.',
    statement: 'Actual conditioning, team and game count; trunk/support and recovery add-ons do not create hard conditioning.',
    applicableScenarios: ['inseason-mixed-team-accounting', 'hamstring-restriction-mixed'],
    expectation: { actualContentOnly: true },
  },
  {
    id: 'ALL-EXPOSURE-REGION-01', category: 'exposure', section: 'Effective strength regions',
    anchorQuote: 'I generally break it down into hinge, squat, push',
    statement: 'Squat/hinge create lower fatigue, push/pull upper fatigue, and combined content credits both.',
    applicableScenarios: ['inseason-mixed-team-accounting', 'hamstring-restriction-mixed'],
    expectation: { lowerPatterns: ['squat', 'hinge'], upperPatterns: ['push', 'pull'], fullBodyNeutral: false },
  },
  {
    id: 'ALL-EXPOSURE-CAPS-01', category: 'exposure', section: 'Weekly caps',
    anchorQuote: 'The app should not normally program more than:\n4 main strength sessions per week',
    statement: 'Selected healthy weeks stay within independently authored strength, running, sprint/COD and hard-day caps.',
    applicableScenarios: ['inseason-mixed-team-accounting'],
    expectation: { maxMainStrength: 4, maxRunning: 4, maxSprintCod: 3, maxHardDays: 4 },
  },
  {
    id: 'OS-COND-CROSS-WEEK-01', category: 'conditioning', section: 'Off-season conditioning continuity',
    anchorQuote: 'early off season = no running and only light aerobic work / base building work.',
    statement: 'Equivalent early off-season allocations retain the same feasible conditioning contract across microcycles, independent of generation path.',
    applicableScenarios: ['early-offseason-legacy-commercial', 'early-offseason-modern-full-gym'],
    expectation: { preserveAllocatedFeasibleComponent: true, exactSessionCountNotRequired: true },
  },
  {
    id: 'ALL-COND-PATH-EQUIV-01', category: 'conditioning', section: 'Deterministic programming authority',
    anchorQuote: 'The app should feel like a smart S&C coach in the background:',
    statement: 'Edge and deterministic fallback paths consume the same feasible allocation and cannot disagree about conditioning presence.',
    applicableScenarios: ['early-offseason-legacy-commercial', 'early-offseason-modern-full-gym', 'early-offseason-explicit-no-cardio', 'early-offseason-row-only'],
    expectation: { equivalentComponentLedger: true },
  },
  {
    id: 'ALL-COND-FEASIBILITY-01', category: 'constraint', section: 'Equipment-aware conditioning',
    anchorQuote: 'Do not force normal gym programming if they are away from equipment.',
    statement: 'One typed feasibility owner resolves, replaces or removes planned conditioning before every generation path.',
    applicableScenarios: ['early-offseason-legacy-commercial', 'early-offseason-modern-full-gym', 'early-offseason-explicit-no-cardio', 'early-offseason-row-only'],
    expectation: { singleOwner: 'conditioningFeasibility', treadmillOffFeet: false, substituteBeforeReduction: true },
  },
  {
    id: 'ALL-COND-NOTE-TRUTH-01', category: 'conditioning', section: 'Coach Notes explain visible changes',
    anchorQuote: 'Coach Notes explain what changed and why.',
    statement: 'A conditioning-specific subphase note requires matching final visible typed conditioning content.',
    applicableScenarios: ['early-offseason-legacy-commercial', 'early-offseason-modern-full-gym', 'early-offseason-explicit-no-cardio', 'early-offseason-row-only'],
    expectation: { visibleEffectRequired: true },
  },
];
