import type { MutationSpec } from '../types';

/** One registry owns mutation intent; individual probes own only isolated injection mechanics. */
export const MUTATION_CATALOGUE: readonly MutationSpec[] = [
  { id: 'composite_lower_single_winner', description: 'Combined lower collapses to one pattern.', affectedRuleIds: ['ALL-STR-BLOCK-01'], expectedInvariantIds: ['INV_HEALTHY_BLOCK_PATTERN_BALANCE'], expectedFirstStage: 'allocation', tier: 'smoke', injectionMethod: 'isolated exported createStrengthIntent patch' },
  { id: 'drop_mixed_conditioning', description: 'Mixed session loses conditioning.', affectedRuleIds: ['ALL-COMP-MIXED-01'], expectedInvariantIds: ['INV_MIXED_PRESERVES_BOTH'], tier: 'smoke', injectionMethod: 'isolated component trace transform' },
  { id: 'drop_team_strength', description: 'Team Training + Strength loses strength.', affectedRuleIds: ['ALL-COMP-TEAM-01'], expectedInvariantIds: ['INV_TEAM_STRENGTH_PRESERVES_BOTH'], tier: 'smoke', injectionMethod: 'isolated component trace transform' },
  { id: 'trunk_as_conditioning', description: 'Trunk support creates conditioning.', affectedRuleIds: ['ALL-TRUNK-SUPPORT-01'], expectedInvariantIds: ['INV_TRUNK_NOT_CONDITIONING'], tier: 'smoke', injectionMethod: 'isolated component trace transform' },
  { id: 'accessory_main_credit', description: 'Accessory session gets main-pattern credit.', affectedRuleIds: ['ALL-ACCESSORY-CREDIT-01'], expectedInvariantIds: ['INV_ACCESSORY_NOT_MAIN_EXPOSURE'], tier: 'smoke', injectionMethod: 'isolated component trace transform' },
  { id: 'full_body_extra_lower', description: 'Full body gains an unplanned second lower pattern.', affectedRuleIds: ['ALL-FULLBODY-01'], expectedInvariantIds: ['INV_FULL_BODY_EXACT_LEDGER'], tier: 'smoke', injectionMethod: 'isolated component trace transform' },
  { id: 'early_power_survives', description: 'Power survives early off-season.', affectedRuleIds: ['OS-PWR-PHASE-01'], expectedInvariantIds: ['INV_POWER_PHASE_GATED'], tier: 'smoke', injectionMethod: 'isolated Slice 3 trace transform' },
  { id: 'contrast_without_heavy', description: 'Contrast survives without a heavy lift.', affectedRuleIds: ['ALL-PWR-CONTRAST-01'], expectedInvariantIds: ['INV_CONTRAST_STRUCTURALLY_VALID'], tier: 'smoke', injectionMethod: 'isolated Slice 3 trace transform' },
  { id: 'offfeet_reported_running', description: 'Off-feet conditioning receives running identity.', affectedRuleIds: ['ALL-COND-MODALITY-01'], expectedInvariantIds: ['INV_MODALITY_IDENTITY_HONEST'], tier: 'smoke', injectionMethod: 'isolated Slice 3 trace transform' },
  { id: 'drop_second_modality', description: 'Second conditioning modality disappears.', affectedRuleIds: ['ALL-COND-MULTI-01'], expectedInvariantIds: ['INV_MULTI_MODALITY_NO_COLLAPSE'], tier: 'smoke', injectionMethod: 'isolated Slice 3 trace transform' },
  { id: 'mixed_strength_fatigue_zero', description: 'Mixed strength contributes no strength fatigue.', affectedRuleIds: ['ALL-EXPOSURE-STRENGTH-01'], expectedInvariantIds: ['INV_STRENGTH_FATIGUE_CREDIT_CONSERVED'], tier: 'smoke', injectionMethod: 'isolated Slice 3 trace transform' },
  { id: 'team_false_squat_credit', description: 'Team anchor creates false squat credit.', affectedRuleIds: ['ALL-ANCHOR-LOAD-01'], expectedInvariantIds: ['INV_TEAM_GAME_ANCHOR_CREDIT_VALID'], tier: 'smoke', injectionMethod: 'isolated Slice 3 trace transform' },
  { id: 'g2_heavy_survives', description: 'Heavy lower survives G-2.', affectedRuleIds: ['ALL-SPACE-G2-LOWER-01'], expectedInvariantIds: ['INV_G2_HEAVY_LOWER_PROTECTED'], tier: 'smoke', injectionMethod: 'isolated Slice 3 trace transform' },
  { id: 'constraint_drops_unrelated', description: 'Constraint removes unaffected content.', affectedRuleIds: ['ALL-CONSTRAINT-AFFECTED-ONLY-01'], expectedInvariantIds: ['INV_UNAFFECTED_CONTENT_PRESERVED'], tier: 'smoke', injectionMethod: 'isolated Slice 3 trace transform' },
  { id: 'equipment_incompatible_survives', description: 'Unavailable equipment survives.', affectedRuleIds: ['ALL-EQUIPMENT-COMPATIBLE-01'], expectedInvariantIds: ['INV_EQUIPMENT_COMPATIBLE'], tier: 'smoke', injectionMethod: 'isolated Slice 3 trace transform' },
  { id: 'trunk_creates_conditioning', description: 'Trunk adds conditioning exposure.', affectedRuleIds: ['ALL-EXPOSURE-COND-01'], expectedInvariantIds: ['INV_CONDITIONING_EXPOSURE_CREDIT_CONSERVED'], tier: 'smoke', injectionMethod: 'isolated Slice 3 trace transform' },
  { id: 'ai_drops_conditioning', description: 'AI fixture drops conditioning.', affectedRuleIds: ['ALL-PATH-EQUIV-01'], expectedInvariantIds: ['INV_EQUIVALENT_CANONICAL_LEDGER'], tier: 'smoke', injectionMethod: 'isolated Slice 4 path transform' },
  { id: 'rebuild_joins_by_weekday', description: 'Rebuild joins by weekday.', affectedRuleIds: ['ALL-REBUILD-IDEMPOTENT-01'], expectedInvariantIds: ['INV_PLAN_ENTRY_JOIN_STABLE_ACROSS_PATHS'], tier: 'smoke', injectionMethod: 'isolated Slice 4 path transform' },
  { id: 'repeat_drops_conditioning', description: 'Repeat Week loses conditioning.', affectedRuleIds: ['ALL-REPEAT-CONSERVE-01'], expectedInvariantIds: ['INV_REPEAT_WEEK_CONSERVES_CONTRACT'], tier: 'smoke', injectionMethod: 'isolated Slice 4 path transform' },
  { id: 'move_replaces_plan_id', description: 'Move replaces plan identity.', affectedRuleIds: ['ALL-MOVE-IDENTITY-01'], expectedInvariantIds: ['INV_MOVE_PRESERVES_PLAN_IDENTITY'], tier: 'smoke', injectionMethod: 'isolated Slice 4 path transform' },
  { id: 'swap_keeps_destination_ids', description: 'Swap keeps destination identities.', affectedRuleIds: ['ALL-SWAP-IDENTITY-01'], expectedInvariantIds: ['INV_SWAP_PRESERVES_BOTH_IDENTITIES'], tier: 'smoke', injectionMethod: 'isolated Slice 4 path transform' },
  { id: 'rehydrate_drops_second_pattern', description: 'Hydration loses secondary pattern.', affectedRuleIds: ['ALL-STORE-ROUNDTRIP-01'], expectedInvariantIds: ['INV_STORE_ROUNDTRIP_CONSERVED'], tier: 'smoke', injectionMethod: 'isolated Slice 4 persistence transform' },
  { id: 'workout_type_overwrites_components', description: 'Scalar workout type overwrites components.', affectedRuleIds: ['ALL-STORE-SCALAR-NONAUTH-01'], expectedInvariantIds: ['INV_SCALAR_FIELDS_NON_AUTHORITATIVE_AFTER_HYDRATE'], tier: 'smoke', injectionMethod: 'isolated Slice 4 persistence transform' },
  { id: 'stale_name_restores_pattern', description: 'Stale display copy restores a pattern.', affectedRuleIds: ['ALL-STORE-SCALAR-NONAUTH-01'], expectedInvariantIds: ['INV_MODERN_TYPED_INTENT_WINS'], tier: 'smoke', injectionMethod: 'isolated Slice 4 persistence transform' },
  { id: 'second_hydration_mutates', description: 'Second hydration changes canonical output.', affectedRuleIds: ['ALL-STORE-IDEMPOTENT-01'], expectedInvariantIds: ['INV_STORE_REHYDRATE_IDEMPOTENT'], tier: 'smoke', injectionMethod: 'isolated Slice 4 persistence transform' },
  { id: 'coach_bike_stays_strength_row', description: 'Coach Bike row stays in strength.', affectedRuleIds: ['ALL-EDIT-CANONICAL-01'], expectedInvariantIds: ['INV_EDIT_USES_CANONICAL_FINALISER'], tier: 'smoke', injectionMethod: 'isolated Slice 4 edit transform' },
  { id: 'contrast_survives_lift_removal', description: 'Contrast metadata survives lift removal.', affectedRuleIds: ['ALL-PWR-CONTENT-01'], expectedInvariantIds: ['INV_EDIT_USES_CANONICAL_FINALISER'], tier: 'smoke', injectionMethod: 'isolated Slice 4 edit transform' },
  { id: 'post_rehydrate_rebuild_drops_component', description: 'Post-hydrate rebuild loses a component.', affectedRuleIds: ['ALL-POST-REHYDRATE-WRITE-01'], expectedInvariantIds: ['INV_POST_REHYDRATE_REBUILD_EQUIVALENT'], tier: 'smoke', injectionMethod: 'isolated Slice 4 persistence transform' },

  { id: 'second_injury_ignored', description: 'Second active injury is ignored.', affectedRuleIds: ['ALL-CONSTRAINT-AFFECTED-ONLY-01'], expectedInvariantIds: ['INV_MULTI_CONSTRAINT_PRESERVED'], tier: 'full', injectionMethod: 'isolated canonical constraint witness transform' },
  { id: 'second_equipment_ignored', description: 'Second equipment constraint is ignored.', affectedRuleIds: ['ALL-EQUIPMENT-COMPATIBLE-01'], expectedInvariantIds: ['INV_MULTI_EQUIPMENT_PRESERVED'], tier: 'full', injectionMethod: 'isolated canonical constraint witness transform' },
  { id: 'recovery_replaces_primary', description: 'Recovery add-on replaces primary content.', affectedRuleIds: ['ALL-RECOVERY-ADDON-01'], expectedInvariantIds: ['INV_RECOVERY_NON_DESTRUCTIVE'], tier: 'full', injectionMethod: 'isolated canonical ledger transform' },
  { id: 'weekly_projection_drops_component', description: 'Weekly projection drops conditioning while detail remains correct.', affectedRuleIds: ['ALL-COMP-PROJECTION-01'], expectedInvariantIds: ['INV_WEEK_DETAIL_COMPONENT_AGREEMENT'], tier: 'full', injectionMethod: 'isolated visible ledger transform' },
  { id: 'detail_projection_drops_component', description: 'Detail projection drops conditioning while weekly remains correct.', affectedRuleIds: ['ALL-COMP-PROJECTION-01'], expectedInvariantIds: ['INV_WEEK_DETAIL_COMPONENT_AGREEMENT'], tier: 'full', injectionMethod: 'isolated visible ledger transform' },
  { id: 'exposure_uses_stale_workout_type', description: 'Exposure accounting trusts stale workoutType.', affectedRuleIds: ['ALL-EXPOSURE-STRENGTH-01'], expectedInvariantIds: ['INV_EXPOSURE_TYPED_COMPONENTS'], tier: 'full', injectionMethod: 'isolated exposure ledger transform' },
  { id: 'planned_credit_after_effective_removal', description: 'Planned pattern remains credited after content removal.', affectedRuleIds: ['ALL-EXPOSURE-REGION-01'], expectedInvariantIds: ['INV_EFFECTIVE_CREDIT_ONLY'], tier: 'full', injectionMethod: 'isolated canonical strength ledger transform' },
  { id: 'canonical_restores_safety_removed_work', description: 'Canonicalisation restores safety-removed work.', affectedRuleIds: ['ALL-CONSTRAINT-AFFECTED-ONLY-01'], expectedInvariantIds: ['INV_SAFETY_REMOVAL_STABLE'], tier: 'full', injectionMethod: 'isolated constrained workout transform' },
  { id: 'deload_drops_pattern_presence', description: 'Deload erases a required block pattern.', affectedRuleIds: ['ALL-STR-BLOCK-01'], expectedInvariantIds: ['INV_DELOAD_PATTERN_CONSERVED'], tier: 'full', injectionMethod: 'isolated generated allocation ledger transform' },
  { id: 'bye_drops_strength_intent', description: 'Bye removes required strength intent.', affectedRuleIds: ['IS-STR-MIN-01'], expectedInvariantIds: ['INV_BYE_STRENGTH_CONSERVED'], tier: 'full', injectionMethod: 'isolated generated allocation ledger transform' },
  { id: 'duplicate_plan_entry_join', description: 'Duplicate planEntryId makes joins ambiguous.', affectedRuleIds: ['ALL-MOVE-IDENTITY-01'], expectedInvariantIds: ['INV_PLAN_ENTRY_JOIN_UNAMBIGUOUS'], tier: 'full', injectionMethod: 'isolated canonical week transform' },
  { id: 'conditioning_duration_drops_on_store', description: 'Conditioning duration disappears during persistence.', affectedRuleIds: ['ALL-STORE-ROUNDTRIP-01'], expectedInvariantIds: ['INV_CONDITIONING_DURATION_CONSERVED'], tier: 'full', injectionMethod: 'isolated persisted ledger transform' },
];

export const SMOKE_MUTATIONS = MUTATION_CATALOGUE.filter((entry) => entry.tier === 'smoke');
export const FULL_MUTATIONS = MUTATION_CATALOGUE;

export function verifyMutationCatalogue(): void {
  const ids = new Set(MUTATION_CATALOGUE.map((entry) => entry.id));
  if (ids.size !== MUTATION_CATALOGUE.length) throw new Error('Mutation catalogue IDs must be unique');
  if (SMOKE_MUTATIONS.length !== 28) throw new Error(`Expected 28 accepted smoke mutations, found ${SMOKE_MUTATIONS.length}`);
  if (MUTATION_CATALOGUE.length < 38) throw new Error(`Expected at least 38 total mutations, found ${MUTATION_CATALOGUE.length}`);
}
