import type { StrengthGoldenScenario } from '../types';

const HEALTHY_IN_SEASON_PROFILE: Record<string, unknown> = {
  firstName: 'BibleHarness',
  ageRange: '25-34',
  position: 'inside_mid',
  motivation: 'Get stronger and stay fit for football',
  goals: ['Build Strength', 'Improve Fitness'],
  experienceLevel: 'Intermediate',
  squatStrength: '1.5x BW',
  benchStrength: '1x BW',
  conditioningLevel: 'Good',
  sprintExposure: '2+ times per week',
  recentTrainingLoad: 'Very consistent',
  injuries: [],
  seasonPhase: 'In-season',
  trainingDaysPerWeek: 5,
  preferredTrainingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  teamTrainingDaysPerWeek: 2,
  teamTrainingDays: ['Tuesday', 'Thursday'],
  teamTrainingIntensity: 'High',
  teamTrainingDuration: '90 min',
  usualGameDay: 'Saturday',
  gameDay: 'Saturday',
  sessionDurationMinutes: 60,
  trainingLocation: 'Commercial gym',
  equipment: ['Full Gym'],
};

export const STRENGTH_GOLDEN_SCENARIOS: readonly StrengthGoldenScenario[] = [
  {
    id: 'is-healthy-5d-tt2-game-sat',
    description: 'Healthy in-season athlete, five available days, Tuesday/Thursday team training and Saturday game.',
    referenceDate: '2026-03-23',
    timezone: 'Australia/Melbourne',
    profile: { ...HEALTHY_IN_SEASON_PROFILE },
    ruleIds: ['ALL-STR-BLOCK-01', 'IS-STR-MIN-01', 'ALL-ACCESSORY-01'],
    expectedAccessoryDays: ['Friday'],
  },
  {
    id: 'is-low-availability-full-body',
    description: 'Healthy, uninjured in-season athlete with one available day and conservative readiness, using the Bible-supported compact full-body structure.',
    referenceDate: '2026-03-23',
    timezone: 'Australia/Melbourne',
    profile: {
      ...HEALTHY_IN_SEASON_PROFILE,
      trainingDaysPerWeek: 1,
      preferredTrainingDays: ['Monday'],
      teamTrainingDaysPerWeek: 0,
      teamTrainingDays: [],
      conditioningLevel: 'Poor',
      sprintExposure: 'No sprint training',
      recentTrainingLoad: 'Hardly at all',
    },
    ruleIds: ['ALL-FULLBODY-01'],
    expectedFullBodyDays: ['Monday'],
  },
  {
    id: 'is-display-copy-non-authoritative',
    description: 'Healthy in-season block with deliberately misleading focus and workout-name copy.',
    referenceDate: '2026-03-23',
    timezone: 'Australia/Melbourne',
    profile: { ...HEALTHY_IN_SEASON_PROFILE },
    ruleIds: ['ALL-STR-BLOCK-01', 'IS-STR-MIN-01', 'ALL-ACCESSORY-01'],
    expectedAccessoryDays: ['Friday'],
    displayMutation: {
      targetDay: 'Monday',
      focus: 'Misleading display copy: Upper Push only',
      workoutName: 'Renamed Session — display text only',
    },
  },
];
