import type { OnboardingData } from '../../types/domain';

export const DEV_E2E_STANDARD_PROFILE: OnboardingData = {
  firstName: 'Sam',
  heightCm: 184,
  weightKg: 90,
  position: 'inside_mid',
  motivation: 'Stay injury-free',
  goals: ['Stay injury-free'],
  seasonPhase: 'In-season',
  gameDay: 'Saturday',
  usualGameDay: 'Saturday',
  teamTrainingDaysPerWeek: 2,
  teamTrainingDays: ['Tuesday', 'Thursday'],
  teamTrainingDuration: '90 minutes',
  teamTrainingIntensity: 'Moderate',
  trainingDaysPerWeek: 5,
  preferredTrainingDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
  sessionDurationMinutes: 60,
  trainingLocation: 'Commercial gym',
  equipmentSelectionCompleteness: 'complete',
  equipment: [
    'barbell',
    'dumbbells',
    'squat_rack',
    'pullup_bar',
    'cable_machine',
    'hamstring_curl',
    'knee_extension',
    'bands',
  ],
  experienceLevel: '5+ years',
  squatStrength: '1.5x bodyweight',
  benchStrength: '1.5x bodyweight+',
  conditioningLevel: 'Elite',
  sprintExposure: '2+ times per week',
  recentTrainingLoad: 'Very consistent',
  injuries: [],
  biggestLimitation: 'Power & explosiveness',
  biggestFrustration: 'Getting a week that respects team training and game day.',
  successVision: 'A durable in-season week that keeps strength and conditioning ticking over without cooking the legs.',
};
