import type { MetamorphicRelationSpec } from '../types';

/** Exactly thirty permanent relations authored independently of production helpers. */
export const METAMORPHIC_RELATIONS: readonly MetamorphicRelationSpec[] = [
  { id: 'reorder-planned-patterns', description: 'Reordering planned patterns does not change meaning.', domain: 'strength', ruleIds: ['ALL-STR-BLOCK-01'], smoke: true },
  { id: 'reorder-components', description: 'Reordering components does not change meaning.', domain: 'components', ruleIds: ['ALL-COMP-PROJECTION-01'], smoke: true },
  { id: 'rename-workout', description: 'Renaming does not change typed intent.', domain: 'strength', ruleIds: ['ALL-STORE-SCALAR-NONAUTH-01'], smoke: true },
  { id: 'change-focus-copy', description: 'Focus copy does not change typed intent.', domain: 'strength', ruleIds: ['ALL-STORE-SCALAR-NONAUTH-01'], smoke: true },
  { id: 'add-hinge-keeps-squat', description: 'Adding hinge cannot remove squat.', domain: 'strength', ruleIds: ['ALL-STR-BLOCK-01'], smoke: true },
  { id: 'add-pull-keeps-push', description: 'Adding pull cannot remove push.', domain: 'strength', ruleIds: ['ALL-STR-BLOCK-01'], smoke: false },
  { id: 'add-conditioning-keeps-strength', description: 'Adding conditioning produces both components.', domain: 'components', ruleIds: ['ALL-COMP-MIXED-01'], smoke: false },
  { id: 'add-trunk-not-conditioning', description: 'Adding support does not create conditioning.', domain: 'components', ruleIds: ['ALL-TRUNK-SUPPORT-01'], smoke: false },
  { id: 'add-recovery-keeps-main', description: 'Adding recovery does not replace the main session.', domain: 'components', ruleIds: ['ALL-RECOVERY-ADDON-01'], smoke: false },
  { id: 'move-keeps-identity', description: 'Moving preserves plan identity.', domain: 'placement', ruleIds: ['ALL-MOVE-IDENTITY-01'], smoke: false },
  { id: 'swap-keeps-identities', description: 'Swapping preserves both plan identities.', domain: 'placement', ruleIds: ['ALL-SWAP-IDENTITY-01'], smoke: false },
  { id: 'remove-strength-mixed-to-conditioning', description: 'Removing final strength changes Mixed to Conditioning.', domain: 'edits', ruleIds: ['ALL-EDIT-CANONICAL-01'], smoke: false },
  { id: 'remove-heavy-invalidates-contrast', description: 'Removing the heavy lift invalidates Contrast.', domain: 'power', ruleIds: ['ALL-PWR-CONTENT-01'], smoke: false },
  { id: 'injury-removes-affected-only', description: 'Injury restriction removes only affected work.', domain: 'constraints', ruleIds: ['ALL-CONSTRAINT-AFFECTED-ONLY-01'], smoke: false },
  { id: 'less-equipment-no-new-requirement', description: 'Reducing equipment cannot create unavailable work.', domain: 'constraints', ruleIds: ['ALL-EQUIPMENT-COMPATIBLE-01'], smoke: false },
  { id: 'more-equipment-no-contract-loss', description: 'Adding equipment does not reduce valid intent.', domain: 'constraints', ruleIds: ['ALL-EQUIPMENT-COMPATIBLE-01'], smoke: false },
  { id: 'low-readiness-no-hard-increase', description: 'Low readiness cannot increase hard load.', domain: 'constraints', ruleIds: ['ALL-READINESS-DOWNGRADE-01'], smoke: false },
  { id: 'copy-no-exposure-change', description: 'Visible copy cannot change exposure accounting.', domain: 'strength', ruleIds: ['ALL-EXPOSURE-STRENGTH-01'], smoke: false },
  { id: 'rehydrate-preserves-contract', description: 'Serialise and rehydrate preserves typed intent.', domain: 'edits', ruleIds: ['ALL-STORE-ROUNDTRIP-01'], smoke: false },
  { id: 'rehydrate-twice-idempotent', description: 'Hydrating twice equals hydrating once.', domain: 'edits', ruleIds: ['ALL-STORE-IDEMPOTENT-01'], smoke: false },
  { id: 'noop-rebuild-equivalent', description: 'No-op rebuild preserves canonical meaning.', domain: 'edits', ruleIds: ['ALL-REBUILD-IDEMPOTENT-01'], smoke: false },
  { id: 'repeat-preserves-source', description: 'Repeat Week preserves the source contract.', domain: 'edits', ruleIds: ['ALL-REPEAT-CONSERVE-01'], smoke: false },
  { id: 'ai-deterministic-same-invariants', description: 'AI fixture and deterministic output satisfy the same rules.', domain: 'edits', ruleIds: ['ALL-PATH-EQUIV-01'], smoke: false },
  { id: 'game-sat-to-sun-spacing', description: 'Game shift changes G-relative protection but not block pattern balance.', domain: 'placement', ruleIds: ['ALL-SPACE-G2-LOWER-01', 'ALL-STR-BLOCK-01'], smoke: false },
  { id: 'bye-relaxes-not-erases', description: 'Bye may relax spacing but cannot erase block strength intent.', domain: 'placement', ruleIds: ['ALL-STR-BLOCK-01'], smoke: false },
  { id: 'deload-reduces-not-invents', description: 'Deload reduces dose without inventing patterns or components.', domain: 'strength', ruleIds: ['ALL-STR-BLOCK-01'], smoke: false },
  { id: 'availability-monotonic-useful-work', description: 'More availability cannot reduce mandatory work without evidence.', domain: 'placement', ruleIds: ['IS-STR-MIN-01'], smoke: false },
  { id: 'add-modality-keeps-existing', description: 'Adding a conditioning modality cannot delete an existing one.', domain: 'conditioning', ruleIds: ['ALL-COND-MULTI-01'], smoke: false },
  { id: 'restriction-monotonic-forbidden', description: 'Adding a restriction cannot increase forbidden exposure.', domain: 'constraints', ruleIds: ['ALL-CONSTRAINT-AFFECTED-ONLY-01'], smoke: false },
  { id: 'canonicalise-idempotent', description: 'Canonicalising a canonical workout is equivalent.', domain: 'edits', ruleIds: ['ALL-EDIT-CANONICAL-01'], smoke: true },
];
