require('sucrase/register');if(process.env.WHOLE_WEEK_MUTATION)require('../../scripts/test-whole-week-mutations.cjs').installMutation(process.env.WHOLE_WEEK_MUTATION);const assert=require('node:assert/strict');global.__DEV__=true;process.env.TZ='Australia/Melbourne';const disk=new Map();global.window={localStorage:{getItem:k=>disk.get(k)??null,setItem:(k,v)=>disk.set(k,v),removeItem:k=>disk.delete(k),clear:()=>disk.clear()}};global.fetch=()=>{throw Error('Offline whole-week planning test')};
const j=require('./support/athleteJourney'),{athleteAnswers}=require('./compilerYear/catalog'),{deriveVisibleWeekLive}=require('../utils/deriveVisibleWeek'),{getSessionComponentRows}=require('../utils/sessionComponents'),{visibleSignature}=require('./compilerYear/invariants');
const start='2026-09-28';const failures=[];let passed=0;async function test(name,fn){if(process.env.WHOLE_WEEK_FILTER&&!name.includes(process.env.WHOLE_WEEK_FILTER))return;try{await fn();console.log('PASS '+name);passed++}catch(e){console.error('FAIL '+name+' '+e.stack);failures.push(name)}}
(async()=>{for(const gender of ['male','female'])await test(gender+' three strength sessions with four equipment days and separate Saturday Speed',async()=>{
 disk.clear();const profile={...athleteAnswers({id:'joint-'+gender,gender,days:['Monday','Tuesday','Wednesday','Friday'],experience:'2-5 years',equipment:'commercial',initialPhase:'In-season',clubDays:['Tuesday','Thursday'],gameDay:'Saturday',extraGame:false}),trainingDaysPerWeek:3,sprintExposure:'2+ times per week'};
 const init=await j.quietAsync(()=>j.coldStartThroughOnboarding({profile,installDayISO:start}));assert.equal(init.onboardingRefusal,null);
 const store=require('../store/programStore').useProgramStore;const removed=await j.quietAsync(()=>require('../store/fixtureMutationTransaction').executeFixtureMutationTransaction({action:'remove',fixtureKind:'game',sourceDate:'2026-10-03',expectedAcceptedRevision:store.getState().acceptedMaterialContext.revision,source:{requestedBy:'athlete',producer:'tap',surface:'program_tab',commandId:'joint-bye-'+gender},todayISO:start}));assert.equal(removed.outcome,'accepted',JSON.stringify(removed));
 const days=j.quiet(()=>deriveVisibleWeekLive(start,start));const parts=d=>d.workout?getSessionComponentRows(d.workout):{strengthRows:[],speedRows:[]};
 console.log('REACHED',JSON.stringify(days.map(d=>({date:d.date,name:d.workout?.name,lifts:parts(d).strengthRows.length,speed:parts(d).speedRows.length}))));
 const lifts=days.filter(d=>parts(d).strengthRows.length);assert.equal(lifts.length,3,'equipment access does not increase strength frequency');assert.ok(lifts.every(d=>profile.preferredTrainingDays.includes(new Date(d.date+'T12:00:00Z').toLocaleDateString('en-US',{weekday:'long',timeZone:'UTC'}))));
 assert.deepEqual(days.filter(d=>parts(d).speedRows.length).map(d=>d.date),['2026-10-03']);assert.equal(parts(days.find(d=>d.date==='2026-09-29')).strengthRows.length>0,true,'pull/push may share team training to free a day');
 assert.equal(parts(days.find(d=>d.date==='2026-09-30')).strengthRows.length,0,'Wednesday is freed');
 const friday=days.find(d=>d.date==='2026-10-02').workout;assert.ok(getSessionComponentRows(friday).conditioningRows.length>0,'Friday retains a separate metabolic prescription');assert.equal(friday.conditioningCategory,'repeat_sprint','bye retains its hard metabolic quality');assert.ok(friday.conditioningBlock?.modality!=='run','bye metabolic work uses available machines');
 const before=visibleSignature(days);assert.ok((await j.quietAsync(()=>j.relaunchApp({storage:disk,todayISO:start}))).ok);assert.equal(visibleSignature(j.quiet(()=>deriveVisibleWeekLive(start,start))),before);
});
for(const [label,access,target,phase,blocked]of [
 ['original MWF bye',['Monday','Wednesday','Friday'],3,'In-season',[]],
 ['Saturday unavailable',['Monday','Tuesday','Wednesday','Friday'],3,'In-season',['Saturday']],
 ['two strength six equipment',['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],2,'Pre-season',[]],
 ['four strength five equipment',['Monday','Tuesday','Wednesday','Thursday','Friday'],4,'Pre-season',[]],
 ['three strength five equipment',['Monday','Tuesday','Wednesday','Thursday','Friday'],3,'Off-season',[]],
 ['five strength six equipment',['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],5,'Off-season',[]],
])await test(label+' preserves access, frequency, work and restart',async()=>{
 disk.clear();const profile={...athleteAnswers({id:'joint-'+label,gender:'female',days:access,experience:'2-5 years',equipment:'commercial',initialPhase:phase,clubDays:phase==='Off-season'?[]:['Tuesday','Thursday'],gameDay:phase==='In-season'?'Saturday':null,extraGame:false}),trainingDaysPerWeek:target,sprintExposure:'2+ times per week'};
 const init=await j.quietAsync(()=>j.coldStartThroughOnboarding({profile,installDayISO:start}));assert.equal(init.onboardingRefusal,null);
 if(phase==='In-season'){const store=require('../store/programStore').useProgramStore;const r=await j.quietAsync(()=>require('../store/fixtureMutationTransaction').executeFixtureMutationTransaction({action:'remove',fixtureKind:'game',sourceDate:'2026-10-03',expectedAcceptedRevision:store.getState().acceptedMaterialContext.revision,source:{requestedBy:'athlete',producer:'tap',surface:'program_tab',commandId:'bye-'+label},todayISO:start}));assert.equal(r.outcome,'accepted')}
 if(blocked.length){const {createTemporaryScheduleFact,temporaryFactScope}=require('../rules/temporarySourceFact');const fact=createTemporaryScheduleFact({observedDate:start,scope:temporaryFactScope({kind:'week',date:start}),scheduleKind:'unavailable_dates',unavailableDates:['2026-10-03'],sourceSurface:'program_tab',factId:'joint-unavailable'});const r=await j.quietAsync(()=>require('../store/temporarySourceFactTransaction').transactTemporarySourceFact({operation:'create',fact,todayISO:start}));assert.equal(r.outcome,'created_and_recomposed',JSON.stringify(r));}
 const days=j.quiet(()=>deriveVisibleWeekLive(start,start));const lifts=days.filter(d=>d.workout&&getSessionComponentRows(d.workout).strengthRows.length&&!d.workout.composedOptional);console.log('REACHED',label,JSON.stringify(days.map(d=>[d.date,d.workout?.name,getSessionComponentRows(d.workout).strengthRows.length])));
 assert.ok(lifts.length<=target,'access never raises target');assert.ok(lifts.length>=Math.min(2,target),'retains useful strength');for(const d of lifts){const name=new Date(d.date+'T12:00:00Z').toLocaleDateString('en-US',{weekday:'long',timeZone:'UTC'});assert.ok(access.includes(name),'never invent equipment access');assert.ok(!blocked.includes(name),'unavailable excludes strength')}
 if(blocked.includes('Saturday'))assert.equal(getSessionComponentRows(days.find(d=>d.date==='2026-10-03').workout).speedRows.length,0);
 if(label==='original MWF bye')assert.equal(getSessionComponentRows(days.find(d=>d.date==='2026-09-29').workout).strengthRows.length,0,'Tuesday access is not invented');
 const before=visibleSignature(days);assert.ok((await j.quietAsync(()=>j.relaunchApp({storage:disk,todayISO:start}))).ok);assert.equal(visibleSignature(j.quiet(()=>deriveVisibleWeekLive(start,start))),before);
});
await test('consecutive fixtures preserve required strength before compactness',async()=>{
 disk.clear();const date='2026-03-23';const {ARCHETYPES}=require('./compilerYear/catalog');const profile=athleteAnswers({...ARCHETYPES.find(a=>a.id==='male-5-two-fixtures'),initialPhase:'In-season',gameDay:'Saturday'});
 assert.equal((await j.quietAsync(()=>j.coldStartThroughOnboarding({profile,installDayISO:date}))).onboardingRefusal,null);
 const store=require('../store/programStore').useProgramStore;const r=await j.quietAsync(()=>require('../store/fixtureMutationTransaction').executeFixtureMutationTransaction({action:'add',fixtureKind:'game',targetDate:'2026-03-27',expectedAcceptedRevision:store.getState().acceptedMaterialContext.revision,source:{requestedBy:'athlete',producer:'tap',surface:'program_tab',commandId:'joint-two-games'},todayISO:date}));assert.equal(r.outcome,'accepted',JSON.stringify(r));
 const days=j.quiet(()=>deriveVisibleWeekLive(date,date));assert.deepEqual(days.filter(d=>d.workout?.workoutType==='Game').map(d=>d.date),['2026-03-27','2026-03-28']);
 const {validateProgramWeek,validatorDaysFromResolvedWeek}=require('../rules/weekStructureValidator');const report=validateProgramWeek({days:validatorDaysFromResolvedWeek(days),anchors:{gameDates:['2026-03-27','2026-03-28']},profile});const unsafe=report.findings.filter(f=>['strong','hard_stop'].includes(f.severity)&&(/^(g1_|g2_)/).test(f.ruleId));assert.deepEqual(unsafe,[],'A compact but incomplete strength trial must not leave old heavy lower work on G-2');
 const before=visibleSignature(days);assert.ok((await j.quietAsync(()=>j.relaunchApp({storage:disk,todayISO:date}))).ok);assert.equal(visibleSignature(j.quiet(()=>deriveVisibleWeekLive(date,date))),before);
});
await test('frequency changes preserve equipment access through the real profile door and restart',async()=>{
 disk.clear();const access=['Monday','Tuesday','Wednesday','Friday'];const profile={...athleteAnswers({id:'joint-settings',gender:'female',days:access,experience:'2-5 years',equipment:'commercial',initialPhase:'Pre-season',clubDays:[],gameDay:null,extraGame:false}),trainingDaysPerWeek:3};
 assert.equal((await j.quietAsync(()=>j.coldStartThroughOnboarding({profile,installDayISO:start}))).onboardingRefusal,null);
 const {commitmentPatchFor}=require('../rules/weeklyCommitmentQuestion');const weekOrder=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];assert.deepEqual(commitmentPatchFor({profile,sessionsPerWeek:2,weekOrder}).preferredTrainingDays,access);
 const p=require('../store/profileStore').useProfileStore;
 const changed=await j.quietAsync(()=>require('./support/settingsJourney').changeProgramSetup({edit:{preferredDays:[...access,'Saturday']},todayISO:start}));assert.ok(changed.ok,JSON.stringify(changed));assert.equal(p.getState().onboardingData.trainingDaysPerWeek,3);
 const r=await j.quietAsync(()=>require('../store/weeklyCommitmentAnswer').confirmWeeklyCommitment({forBlockNumber:1,sessionsPerWeek:2,profile:p.getState().onboardingData,todayISO:start}));assert.ok(r.ok,JSON.stringify(r));assert.equal(p.getState().onboardingData.trainingDaysPerWeek,2);assert.deepEqual(p.getState().onboardingData.preferredTrainingDays,[...access,'Saturday']);
 const days=j.quiet(()=>deriveVisibleWeekLive(start,start));assert.equal(days.filter(d=>getSessionComponentRows(d.workout).strengthRows.length>0&&!d.workout.composedOptional).length,2);
 const before=visibleSignature(days);assert.ok((await j.quietAsync(()=>j.relaunchApp({storage:disk,todayISO:start}))).ok);assert.equal(p.getState().onboardingData.trainingDaysPerWeek,2);assert.deepEqual(p.getState().onboardingData.preferredTrainingDays,[...access,'Saturday']);assert.equal(visibleSignature(j.quiet(()=>deriveVisibleWeekLive(start,start))),before);
});
console.log(`Whole-week journey: ${passed}/${passed+failures.length}`);if(failures.length)process.exitCode=1})();
