/**
 * Central type exports for Local Footy Athlete
 * All types used across the application
 */

// Domain types
export type {
  Position,
  ExperienceLevel,
  SubscriptionStatus,
  TrainingLocation,
  ProgramPhase,
  WorkoutType,
  ExerciseType,
  DifficultyLevel,
  ScheduleEventType,
  CoachMessageRole,
  IntensityLevel,
  AttachedConditioningKind,
} from './domain';

export type {
  UserProfile,
  TrainingProgram,
  Microcycle,
  Workout,
  WorkoutExercise,
  Exercise,
  LoggedWorkout,
  LoggedSet,
  CoachConversation,
  CoachMessage,
  ScheduleEvent,
  WeeklySummary,
  TrainingStats,
  PersonalRecord,
} from './domain';

// Navigation types
export type {
  RootStackParamList,
  AuthStackParamList,
  OnboardingStackParamList,
  AppTabParamList,
  HomeStackParamList,
  ProgramStackParamList,
  JournalStackParamList,
  CoachStackParamList,
  ProfileStackParamList,
  ModalStackParamList,
  NavigationState,
  ExerciseFilters,
  LogWorkoutParams,
  CreateProgramParams,
  LinkingConfig,
} from './navigation';

export { DeepLinkPath } from './navigation';

// API types
export type {
  ApiResponse,
  ApiError,
  PaginationParams,
  PaginatedResponse,
  SignUpRequest,
  SignUpResponse,
  SignInRequest,
  SignInResponse,
  ForgotPasswordRequest,
  ResetPasswordRequest,
  RefreshTokenRequest,
  SignOutRequest,
  GetUserProfileResponse,
  UpdateUserProfileRequest,
  UpdateUserProfileResponse,
  CreateUserProfileRequest,
  GetTrainingProgramResponse,
  ListTrainingProgramsResponse,
  CreateTrainingProgramRequest,
  CreateTrainingProgramResponse,
  UpdateTrainingProgramRequest,
  UpdateTrainingProgramResponse,
  DeleteTrainingProgramRequest,
  DeleteTrainingProgramResponse,
  GetMicrocycleResponse,
  ListMicrocyclesResponse,
  CreateMicrocycleRequest,
  CreateMicrocycleResponse,
  UpdateMicrocycleRequest,
  UpdateMicrocycleResponse,
  GetWorkoutResponse,
  ListWorkoutsResponse,
  CreateWorkoutRequest,
  CreateWorkoutResponse,
  UpdateWorkoutRequest,
  UpdateWorkoutResponse,
  DeleteWorkoutRequest,
  DeleteWorkoutResponse,
  GetWorkoutExerciseResponse,
  ListWorkoutExercisesResponse,
  CreateWorkoutExerciseRequest,
  CreateWorkoutExerciseResponse,
  UpdateWorkoutExerciseRequest,
  UpdateWorkoutExerciseResponse,
  DeleteWorkoutExerciseRequest,
  DeleteWorkoutExerciseResponse,
  GetExerciseResponse,
  ListExercisesRequest,
  ListExercisesResponse,
  CreateExerciseRequest,
  CreateExerciseResponse,
  UpdateExerciseRequest,
  UpdateExerciseResponse,
  GetLoggedWorkoutResponse,
  ListLoggedWorkoutsRequest,
  ListLoggedWorkoutsResponse,
  CreateLoggedWorkoutRequest,
  CreateLoggedWorkoutResponse,
  UpdateLoggedWorkoutRequest,
  UpdateLoggedWorkoutResponse,
  CompleteLoggedWorkoutRequest,
  CompleteLoggedWorkoutResponse,
  GetLoggedSetResponse,
  ListLoggedSetsResponse,
  CreateLoggedSetRequest,
  CreateLoggedSetResponse,
  UpdateLoggedSetRequest,
  UpdateLoggedSetResponse,
  GetCoachConversationResponse,
  ListCoachConversationsResponse,
  CreateCoachConversationRequest,
  CreateCoachConversationResponse,
  UpdateCoachConversationRequest,
  UpdateCoachConversationResponse,
  GetCoachMessageResponse,
  ListCoachMessagesResponse,
  SendCoachMessageRequest,
  SendCoachMessageResponse,
  StreamCoachMessageRequest,
  StreamCoachMessageChunk,
  GetScheduleEventResponse,
  ListScheduleEventsRequest,
  ListScheduleEventsResponse,
  CreateScheduleEventRequest,
  CreateScheduleEventResponse,
  UpdateScheduleEventRequest,
  UpdateScheduleEventResponse,
  DeleteScheduleEventRequest,
  DeleteScheduleEventResponse,
  BulkCreateLoggedSetsRequest,
  BulkCreateLoggedSetsResponse,
  BulkUpdateLoggedSetsRequest,
  BulkUpdateLoggedSetsResponse,
  TrainingStatsRequest,
  TrainingStatsResponse,
  ProgressChartDataRequest,
  ProgressChartDataResponse,
  SyncLoggedWorkoutRequest,
  SyncLoggedWorkoutResponse,
  BulkSyncLoggedWorkoutsRequest,
  BulkSyncLoggedWorkoutsResponse,
} from './api';

export { ApiErrorCode } from './api';
