import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';
import { COACH_KNOWLEDGE_SOURCE_SPECS } from '../src/rules/coachKnowledgeManifest';

const OUTPUT_PATH = 'supabase/functions/coach-chat/canonicalCoachKnowledge.generated.ts';
const sources = COACH_KNOWLEDGE_SOURCE_SPECS.map((source) => ({
  ...source,
  content: readFileSync(resolve(process.cwd(), source.path), 'utf8'),
}));
const output = `/* GENERATED by scripts/build-coach-knowledge-bundle.ts. Do not edit. */\n`
  + `export const CANONICAL_COACH_KNOWLEDGE = ${JSON.stringify(sources, null, 2)} as const;\n`;

writeFileSync(resolve(process.cwd(), OUTPUT_PATH), output, 'utf8');
console.log(`Built ${OUTPUT_PATH} from ${sources.length} exact canonical sources.`);
