/**
 * GENERATE THE APP MAP THE COACH READS (plan slice S3, 2026-09-10).
 *
 * `src/rules/coachAppMap.ts` imports the signed copy constant for every label,
 * so a renamed button changes this file on the next build and the freshness
 * cell in `test:coach-chat-integration` reds until it is rebuilt. One row per
 * door, in the same `**DOOR-id** · …` shape the registry uses, so the
 * retriever's one-chunk-per-row cutter and the model's citations work
 * unchanged.
 */
import { writeFileSync } from 'fs';
import { resolve } from 'path';
import { COACH_APP_MAP } from '../src/rules/coachAppMap';

const OUTPUT_PATH = 'docs/generated/COACH_APP_MAP.md';

const lines: string[] = [
  '# THE APP MAP — every door the coach may name, generated from the signed labels',
  '',
  'GENERATED by scripts/build-coach-app-map.ts from src/rules/coachAppMap.ts. Do not edit.',
  'Each row: the door id, its exact on-screen label, where it is (tab → screen → control), what it does, and when it serves the athlete.',
  '',
];
for (const door of COACH_APP_MAP) {
  lines.push(
    `**${door.id}** · Label: "${door.label}" · Where: ${door.path.join(' → ')}`
      + (door.options && door.options.length > 0 ? ` · Options: ${door.options.map((option) => `"${option}"`).join(' | ')}` : '')
      + ` · Does: ${door.does} · When: ${door.when}`,
  );
  lines.push('');
}
writeFileSync(resolve(process.cwd(), OUTPUT_PATH), `${lines.join('\n')}\n`, 'utf8');
console.log(`Built ${OUTPUT_PATH} from ${COACH_APP_MAP.length} doors.`);
